### PR TITLE
Main menu scene

### PR DESCRIPTION
**Pull request by duriumm**
Main menu scene

- Pixel art font (choosable in textmeshpro inspector)
- GUI for main menu with clickable buttons
- Main menu, Settings menu and Save Files menu 
- Reimported Frog prefab with correct settings
- Music from Viper added to main menu scene

Lots of sloppy coding in this one, so feel free to be harsh with the review! :)

### CODE REVIEW

**Comment by yousernaym** [comment]
Nice work so far Lasse.
Only suggestion is to use Unitys built-in Toggle component for creating the checkboxes.

**Comment by yousernaym** [comment]
^^It would remove the need to use custom sprites and bool variables to keep track of state, resulting in much cleaner code.
And in the future we should probably use PlayerPrefs to store the settings.

**Comment by duriumm** [comment]
> Nice work so far Lasse.
> Only suggestion is to use Unitys built-in Toggle component for creating the checkboxes.

Can you tell me more about this???

**Comment by yousernaym** [comment]
I dont know much, but instead of adding the Button component, add the Toggle component. The IsOn property determines its state, and instead of a Click event it has the On Value Changed event.
https://docs.unity3d.com/Packages/com.unity.ugui@1.0/manual/script-Toggle.html

**Comment by duriumm** [comment]
> I dont know much, but instead of adding the Button component, add the Toggle component. The IsOn property determines its state, and instead of a Click event it has the On Value Changed event.
> https://docs.unity3d.com/Packages/com.unity.ugui@1.0/manual/script-Toggle.html

Hmm interesting! The onClick is attached as default when creating the button, but i will look into toggle function!

**Comment by yousernaym** [comment]
Yeah, I just saw that you can create a Toggle object with the Toggle component already attached

**Pull request merged**
